### ISSUE TITLE
R_DrawCollision / Map Export

### ISSUE THREAD

**Issue by xoxor4d** [xoxor4d/iw3xo-dev#1]
# DrawCollision
- [x] Implement unlit fake-lighting (just like radiant debug brushes)
- [ ] Fix brush generation for weird angled brushes
- [x] Fix brushmodel/entity brushes accumulating at origin (0, 0, 0)

# Map Export
- [x] Export Brush contents
- [ ] DrawCollision Issue 2
- [x] DrawCollision Issue 3 (brushmodel/trigger/brush entity exporting)
- [ ] Fix brushes that crash radiant upon selecting them (partly fixed by excluding small complex brushes on export)
(Check brush with "isValidBrush" function from radiant before actually writing them to the map file?)
- [x] Implement a way to only export a selected part of a map (e.g. select by drawing a bounding box)
- [ ] Find a way to map collision triangles with gfxworld triangles to get correct material settings for  brushes and "patches"
- [ ] Find a better way to reconstruct patches from triangles.
- [ ] Theres no information of static light entities left in the gfxworld, as they are baked into the lightmap texture. (Ideas?)

**Comment by reaaLx** [comment]
possibility of iw4x .map export? altho .obj exports are around...

**Comment by xoxor4d** [comment]
obv. doable but has nothing to do with this repo
